version: '2'

networks:
  nodered:

services:
  nodered:
    image: ${NODERED_IMAGE}
    networks:
      - nodered
    ports:
      - "${NODERED_PORT}:1880"
    volumes:
      - "./data:/root/.node-red"
    privileged: true
    restart: "unless-stopped"